version: '3.8'

services:
    backend:
        build:
            context: ./server
        # ports:
        #     - '3000:3000'
        env_file:
            - ./server/.env
        environment:
            - REDIS_URL=redis://localhost:6379
        depends_on:
            - redis
        network_mode: 'host'

    redis:
        image: redis/redis-stack:latest
        volumes:
            - redis-data:/data
        # ports:
        #     - '6379:6379'
        network_mode: 'host'

volumes:
    redis-data:
